import "../styles/globals.css";
import Aside from "../components/layout/Aside";
import Header from "../components/layout/Header";
import Main from "../components/layout/Main";
import Footer from "../components/layout/Footer";


export const metadata = {
    title: "ConecteVoc",
    description: "Generated by ConecteVoc",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="grid grid-cols-[15vw_1fr] h-screen">
                <div className="bg-stone-950">
                    <Aside />
                </div>
                <div className="grid grid-rows-[auto_90vh_auto]">
                    <Header />
                    <Main >{children}</Main>
                    <Footer />
                </div>
            </body>
        </html>
    );
}
