server:
  port: 8080

spring:
  datasource:
    platform: postgres
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PWD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    database: POSTGRESQL
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        id.new_generator_mappings: true

#config:
#  uris:
#    react-app-uri: ${REACT_APP_URI}
#
#logging:
#  level:
#    org:
#      springframework:
#        security:
#          - TRACE
#          - oauth2: TRACE

